name: Build

on: 
  push:
    paths-ignore: 
    - '*.md' 
  pull_request: {}
  
jobs:
  build_wheels:
    name: Build wheels for Dimble on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        
    steps:
      - uses: actions/checkout@v3   
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Install dependencies 
        run : | 
          pip install maturin
          pip install . -v
      - name: Build 
        run : | 
          maturin build
      - name: Test 
        run : | 
          pip install -v .[dev] 
          python3 -m pytest
      - uses: actions/upload-artifact@v3
        with:
          path: target/wheels/*.whl
